# Generated by Django 4.0.3 on 2022-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_employee_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
